"""'Init'

Revision ID: 9f779fba5315
Revises: 6bf9fa77a1c0
Create Date: 2024-06-07 21:48:11.241525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f779fba5315'
down_revision: Union[str, None] = '6bf9fa77a1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('mobile', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'mobile')
    # ### end Alembic commands ###
